name: imageprocessor_environment
dependencies:
  - python=3.6
  - pytest
  - pytest-pep8
  - pytest-cov
  - numpy
  - sphinx
  - pandas
  - flask
  - requests
  - pip
  - scikit-image
  - scikit-learn
  - pillow
  - pip:
    - pymodm



